services:
  influxdb:
    image: influxdb:2.7-alpine
    env_file:
      - influxv2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
  telegraf:
    image: telegraf:1.31-alpine
    depends_on:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - influxv2.env

volumes:
  influxdbv2:

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    env_file:
      - grafana.env
    volumes:
      - grafana-data:/var/lib/grafana
